#
#  Copyright 2020-2022 Zeek-Kafka
#  Copyright 2015-2020 The Apache Software Foundation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
FROM centos:8

ARG ZEEK_VERSION
ARG LIBRDKAFKA_VERSION

# install epel for screen
RUN dnf install -y --nodocs epel-release

# copy in the .screenrc
COPY .screenrc /root

# install powertools for libpcap-devel
RUN dnf install -y --nodocs 'dnf-command(config-manager)' \
 && dnf config-manager --set-enabled powertools

# install prereqs then clean dnf cache
RUN dnf -y update \
 && dnf -y --nodocs install bison \
                            cmake \
                            cyrus-sasl \
                            cyrus-sasl-devel \
                            cyrus-sasl-gssapi \
                            flex \
                            gcc \
                            gcc-c++ \
                            git \
                            jq \
                            libpcap \
                            libpcap-devel \
                            make \
                            openssl-devel \
                            perl \
                            platform-python-devel \
                            python3 \
                            screen \
                            swig \
                            tree \
                            vim \
                            zlib-devel \
 && dnf -y clean all

# install zeek (and zkg by default, as of 4.0.0)
WORKDIR /root
RUN git clone https://github.com/zeek/zeek
WORKDIR zeek/
RUN git checkout "v${ZEEK_VERSION}" \
 && git submodule update --init --recursive \
 && ./configure \
 && make -j $(nproc --all || echo 1) \
 && make install \
 && ldconfig
ENV PATH="${PATH}:/usr/local/zeek/bin"
ENV PATH="${PATH}:/usr/bin"

# install pip3 and zkg dependencies
WORKDIR /root
COPY requirements.txt requirements.txt
RUN dnf -y install diffutils \
                   python3-pip \
 && dnf clean all \
 && python3 -m pip install --upgrade pip \
 && python3 -m pip install -r requirements.txt

# install librdkafka
WORKDIR /root
RUN curl -L "https://github.com/edenhill/librdkafka/archive/v${LIBRDKAFKA_VERSION}.tar.gz" | tar xvz
WORKDIR "librdkafka-${LIBRDKAFKA_VERSION}/"
RUN ./configure --enable-sasl --install-deps \
 && make -j $(nproc --all || echo 1) \
 && make install \
 && ldconfig
