#
#  Copyright 2020-2021 Zeek-Kafka
#  Copyright 2015-2020 The Apache Software Foundation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
ARG FROM_IMAGE="ubuntu"
ARG FROM_IMAGE_TAG="20.04"

FROM "${FROM_IMAGE}":"${FROM_IMAGE_TAG}"

ARG ZEEK_VERSION
ARG LIBRDKAFKA_VERSION

# copy in the .screenrc
COPY .screenrc /root

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    bc \
    bison \
    bsdmainutils \
    cmake \
    curl \
    flex \
    g++ \
    gcc \
    git \
    jq \
    lcov \
    libkrb5-dev \
    libmaxminddb-dev \
    libpcap-dev \
    libssl-dev \
    make \
    python3 \
    python3-dev \
    python3-pip\
    ruby \
    screen \
    sqlite3 \
    swig \
    tree \
    unzip \
    vim \
    wget \
    zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install junit2html
RUN gem install coveralls-lcov

# install zeek
WORKDIR /root
RUN git clone https://github.com/zeek/zeek
WORKDIR zeek/
RUN git checkout "v${ZEEK_VERSION}" \
 && git submodule update --init --recursive \
 && ./configure \
 && make -j $(nproc --all || echo 1) && \
 && make \
 && make install \
 && ldconfig
ENV PATH="${PATH}:/usr/local/zeek/bin"
ENV PATH="${PATH}:/usr/bin"

# install pip3 (zkg itself is now available via Zeek)
WORKDIR /root
COPY requirements.txt requirements.txt
RUN apt-get -y install diffutils \
                       python3-pip \
 && apt-get clean all \
 && python3 -m pip install --upgrade pip \
 && python3 -m pip install -r requirements.txt

# install librdkafka
WORKDIR /root
RUN curl -L "https://github.com/edenhill/librdkafka/archive/v${LIBRDKAFKA_VERSION}.tar.gz" | tar xvz
WORKDIR "librdkafka-${LIBRDKAFKA_VERSION}/"
RUN ./configure --enable-sasl --install-deps \
  make -j $(nproc --all || echo 1) && \
 && make \
 && make install
