services:
  zookeeper:
    platform: linux/amd64
    build:
      context: containers/zookeeper
      cache_from:
        - zeek-kafka_zookeeper:latest
        - zookeeper:3.4
    image: zeek-kafka_zookeeper:latest
  kafka-1:
    platform: linux/amd64
    build:
      context: containers/kafka
      cache_from:
        - zeek-kafka_kafka:latest
        - wurstmeister/kafka:2.12-2.5.0
    image: zeek-kafka_kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
  kafka-2:
    platform: linux/amd64
    build:
      context: containers/kafka
      cache_from:
        - zeek-kafka_kafka:latest
        - wurstmeister/kafka:2.12-2.5.0
    image: zeek-kafka_kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
  zeek:
    platform: linux/amd64
    build:
      context: containers/zeek
      dockerfile: Dockerfile.zeek.latest
      cache_from:
        - zeek-kafka_zeek:latest
        - ${ZEEK_KAFKA_OS}
      args:
        LIBRDKAFKA_VERSION: "2.10.1"
    image: zeek-kafka_zeek:latest
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    volumes:
      - "${DATA_PATH}:/root/data"
      - "${TEST_OUTPUT_PATH}:/root/test_output"
      - "${PLUGIN_ROOT_DIR}:/root/code"
      - "${OUR_SCRIPTS_PATH}:/root/built_in_scripts"
    tty: true
